#!/usr/bin/env python3
"""Export the trained avoidance policy for the C++ module, and the reference cases its test checks.

  python cpp/avoid_policy/export_policy.py            write avoid_policy.bin and tests/reference_cases.txt
  python cpp/avoid_policy/export_policy.py --check    exit 1 if avoid_policy.bin is not what
                                                      models/avoid_policy.npz exports to

Weight file (little-endian):
  8 bytes   magic "AVPOL001"
  uint32    number of hidden layers
  per layer, hidden layers first, output layer last:
    uint32 rows, uint32 cols, rows*cols float64 (row-major), rows float64 (bias)

Reference case, one per line, numbers separated by spaces:
  heading  v_des(2)  vel(2)  slot_err(2)  rays(24)  has_nearest  nearest(2)  n  n*(rx ry rvx rvy)
  then the Python results:  observation(47)  action(2)  correction(2)
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(ROOT / "src"))

from swarm_agent.avoidance import (N_RAYS, AvoidInput, LearnedPolicy,  # noqa: E402
                                   action_to_correction, observation)

MAGIC = b"AVPOL001"
NPZ = ROOT / "models" / "avoid_policy.npz"
BIN = HERE / "avoid_policy.bin"
CASES = HERE / "tests" / "reference_cases.txt"
N_CASES = 100
SEED = 0


def weight_bytes(npz_path: Path) -> bytes:
    w = np.load(npz_path)
    n = int(w["n_layers"])
    out = [MAGIC, struct.pack("<I", n)]
    for wk, bk in [(f"W{k}", f"b{k}") for k in range(n)] + [("Wa", "ba")]:
        W = np.ascontiguousarray(w[wk], dtype="<f8")
        b = np.ascontiguousarray(w[bk], dtype="<f8")
        out += [struct.pack("<II", *W.shape), W.tobytes(), b.tobytes()]
    return b"".join(out)


def random_input(rng: np.random.Generator) -> AvoidInput:
    """Covers the branches: clamped slot error, rays beyond range, no obstacle, 0 to 5 neighbours
    (some out of range, so the nearest-three selection is exercised)."""
    nearest = None if rng.random() < 0.3 else tuple(rng.uniform(-25.0, 25.0, 2))
    neighbors = [tuple(rng.uniform(-35.0, 35.0, 2)) + tuple(rng.uniform(-10.0, 10.0, 2))
                 for _ in range(int(rng.integers(0, 6)))]
    return AvoidInput(heading=float(rng.uniform(-np.pi, np.pi)),
                      v_des=tuple(rng.uniform(-10.0, 10.0, 2)),
                      vel=tuple(rng.uniform(-10.0, 10.0, 2)),
                      slot_err=tuple(rng.uniform(-40.0, 40.0, 2)),
                      rays=rng.uniform(0.0, 30.0, N_RAYS),
                      nearest=nearest, neighbors=neighbors)


def case_line(inp: AvoidInput, policy: LearnedPolicy) -> str:
    obs = observation(inp)
    act = policy.act(obs)
    cx, cy = action_to_correction(act, inp.heading)
    f = lambda xs: [format(float(x), ".17g") for x in xs]   # noqa: E731  (17 digits round-trip a double)
    nearest = inp.nearest if inp.nearest is not None else (0.0, 0.0)
    fields = (f([inp.heading, *inp.v_des, *inp.vel, *inp.slot_err]) + f(inp.rays)
              + [str(int(inp.nearest is not None))] + f(nearest) + [str(len(inp.neighbors))]
              + f([x for n in inp.neighbors for x in n])
              + [format(float(x), ".9g") for x in obs] + f(act) + f([cx, cy]))
    return " ".join(fields)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="verify avoid_policy.bin against the .npz, write nothing")
    args = ap.parse_args()

    data = weight_bytes(NPZ)
    if args.check:
        if not BIN.exists() or BIN.read_bytes() != data:
            print(f"{BIN.relative_to(ROOT)} is out of date: run python {Path(__file__).relative_to(ROOT)}")
            return 1
        print(f"{BIN.relative_to(ROOT)} matches {NPZ.relative_to(ROOT)}")
        return 0

    BIN.write_bytes(data)
    policy = LearnedPolicy(NPZ)
    rng = np.random.default_rng(SEED)
    lines = ["# Generated by export_policy.py from models/avoid_policy.npz. Do not edit by hand."]
    lines += [case_line(random_input(rng), policy) for _ in range(N_CASES)]
    CASES.write_text("\n".join(lines) + "\n")
    print(f"wrote {BIN.relative_to(ROOT)} ({len(data)} bytes) and {CASES.relative_to(ROOT)} ({N_CASES} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
